database:
  user: 'root'
  password: '123456'
  host: 'localhost'
  database: 'smart_farm'

#华为云配置
access_key: ''
secret_key: ''
instance_id: ''
project_id: ''
device_id: ''
service_id: ''
region_id: '' #华南广州，请填写"cn-south-1"
endpoint: ''