#数据库应该有一个记录数据的，还需有一个用户库,需根据需要来进行更改
database:
  user: '《user》'
  password: '《password》'
  host: '《host》'
  database: '《database》'

#华为云配置
access_key: ''
secret_key: ''
instance_id: ''
project_id: ''
device_id: ''
service_id: ''
region_id: '' #华南广州，请填写"cn-south-1"
endpoint: ''
